spring:
    servlet:
        multipart:
            max-file-size: 512MB
            max-request-size: 1000MB
    datasource:
        druid:
            default-auto-commit: false
            initial-size: 20
            max-active: 100
            min-idle: 10
        password: tongyi0923
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3310/exam_db?serverTimezone=Asia/Shanghai
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm
        time-zone: GMT+8
    redis:
        host: 127.0.0.1
        password: redispw
        port: 32768
        database: 0
        timeout: 1000
server:
    servlet:
        session:
            cookie:
                http-only: false